import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadCatalog, itemURL, sourceURL } from './catalog.mjs';
import { layout, home, entry, sourcePage, about } from '../site/templates.mjs';

export function build(root = process.cwd(), options = {}) {
  const catalog = loadCatalog(root);
  const base = (options.base ?? process.env.BASE_PATH ?? '').replace(/\/$/, '');
  if (base && !/^\/(?:[A-Za-z0-9_-]+\/?)+$/.test(base)) throw new Error('BASE_PATH must be a simple absolute URL path');
  const repo = process.env.GITHUB_REPOSITORY ? `https://github.com/${process.env.GITHUB_REPOSITORY}` : 'https://github.com/ILetAIWriteThis/graveyard';
  const siteURL = (process.env.SITE_URL || '').replace(/\/$/, '');
  const out = path.join(root, '_site');
  if (fs.existsSync(out)) {
    if (fs.lstatSync(out).isSymbolicLink() || !fs.existsSync(path.join(out, '.graveyard-build'))) throw new Error('Refusing to replace _site without the build marker');
    fs.rmSync(out, { recursive: true });
  }
  fs.mkdirSync(out, { recursive: true });
  fs.writeFileSync(path.join(out, '.graveyard-build'), 'Generated by graveyard. Safe to rebuild.\n');
  const write = (relative, data) => { const file = path.join(out, relative); fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, data); };
  const page = (relative, title, description, body, current = '') => write(relative, layout({ title, description, body, base, current, repo, canonical: siteURL ? `${siteURL}/${relative.replace(/index\.html$/, '')}` : '' }));
  page('index.html', 'Nothing finished. Nothing wasted.', 'A resting place for unfinished projects, passing thoughts, and useful little scraps.', home(catalog, base), 'grounds');
  page('about/index.html', 'Field notes', 'Bring the thing. The caretaker finds it a home.', about(base), 'about');
  for (const item of catalog.published) {
    page(`items/${item.id}/index.html`, item.title, item.summary, entry(item, catalog, base));
    for (const file of item.sourceFiles) page(`items/${item.id}/source/${file.name}.html`, file.name, `Surviving source from ${item.title}.`, sourcePage(item, file, base));
  }
  page('404.html', 'An unmarked grave', 'This path does not lead to a known burial.', `<section class="lost-page shell"><span class="eyebrow">404 · AN UNMARKED GRAVE</span><h1>A wrong turn.<br><em>It happens.</em></h1><p>This path doesn't lead to anything we've buried.</p><a class="button primary" href="${base}/">Back to the gates →</a></section>`);
  for (const name of ['style.css', 'theme.js', 'app.js', 'favicon.svg']) write(`assets/${name}`, fs.readFileSync(path.join(root, 'site', name)));
  const publicData = {
    base, taxonomy: catalog.taxonomy,
    items: catalog.published.map(({ directory, markdown, sourceFiles, related, ...item }) => ({ ...item, related: related.filter(edge => catalog.byId.get(edge.id)?.publish), url: itemURL(item, base), search: [markdown, ...sourceFiles.map(file => file.text)].join('\n'), files: sourceFiles.map(file => ({ name: file.name, url: sourceURL(item, file.name, base) })) })),
  };
  write('assets/catalog.js', `window.GRAVEYARD = ${JSON.stringify(publicData).replaceAll('<', '\\u003c').replaceAll('\u2028', '\\u2028').replaceAll('\u2029', '\\u2029')};\n`);
  write('.nojekyll', '');
  console.log(`Built ${catalog.published.length} burials → _site/ (${base || '/'})`);
  return { catalog, out };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try { build(); } catch (error) { console.error(error.message); process.exitCode = 1; }
}
